```{r}
library("ggplot2")
library("ggpubr")
```

```{r}
ratio = read.csv('../input/iph_total_lipid_ratio.csv')
perc_iph = read.csv('../input/perc_iph.csv')
iph = read.csv('../input/iph_volume.csv')
perc_lipid_iph = read.csv('../input/perc_lipid_minus_iph.csv')
lipid_iph = read.csv('../input/lipid_minus_iph.csv')
perc_mixed = read.csv('../input/perc_mixed.csv')

plots <- list()
```

```{r}
ratio.plot <- ggplot(ratio, aes(volumes, logits)) +
geom_point(color="#003366") +
geom_smooth(span=0.5, se=TRUE, color="#FFC325", fill="#FFE299") +
theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    panel.border = element_rect(colour="black", fill=NA, size=0.5),
    axis.title = element_text(size=14),
    axis.title.x = element_text(margin=margin(t=10)),
    axis.title.y = element_text(margin=margin(r=10)),
    plot.title = element_text(hjust=0.5, size=16, margin=margin(b=10)),
    legend.position = c(0.65, 0.12),
    legend.text = element_text(size=13),
    aspect.ratio = 0.8,
    text = element_text(size = 16, family = "Helvetica")
    ) +
xlab("IPH to lipid volume ratio") +
ylab("Logits of symptoms")

plots <- append(plots, ratio.plot)
```

```{r}
perc.iph.plot <- ggplot(perc_iph, aes(volumes, logits)) +
geom_point(color="#003366") +
geom_smooth(span=0.3, se=TRUE, color="#FFC325", fill="#FFE299") +
theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    panel.border = element_rect(colour="black", fill=NA, size=0.5),
    axis.title = element_text(size=14),
    axis.title.x = element_text(margin=margin(t=10)),
    axis.title.y = element_text(margin=margin(r=10)),
    plot.title = element_text(hjust=0.5, size=16, margin=margin(b=10)),
    legend.position = c(0.65, 0.12),
    legend.text = element_text(size=13),
    aspect.ratio = 0.8,
    text = element_text(size = 16, family = "Helvetica")
    ) +
xlab("IPH volume (%)") +
ylab("Logits of symptoms")

plots <- append(plots, perc.iph.plot)
```

```{r}
iph.plot <- ggplot(iph, aes(volumes, logits)) +
geom_point(color="#003366") +
geom_smooth(span=0.3, se=TRUE, color="#FFC325", fill="#FFE299") +
theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    panel.border = element_rect(colour="black", fill=NA, size=0.5),
    axis.title = element_text(size=14),
    axis.title.x = element_text(margin=margin(t=10)),
    axis.title.y = element_text(margin=margin(r=10)),
    plot.title = element_text(hjust=0.5, size=16, margin=margin(b=10)),
    legend.position = c(0.65, 0.12),
    legend.text = element_text(size=13),
    aspect.ratio = 0.8,
    text = element_text(size = 16, family = "Helvetica")
    ) +
xlab("IPH volume") +
ylab("Logits of symptoms")

plots <- append(plots, iph.plot)
```

```{r}
perc.lipid.iph.plot <- ggplot(perc_lipid_iph, aes(volumes, logits)) +
geom_point(color="#003366") +
geom_smooth(span=0.5, se=TRUE, color="#FFC325", fill="#FFE299") +
theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    panel.border = element_rect(colour="black", fill=NA, size=0.5),
    axis.title = element_text(size=14),
    axis.title.x = element_text(margin=margin(t=10)),
    axis.title.y = element_text(margin=margin(r=10)),
    plot.title = element_text(hjust=0.5, size=16, margin=margin(b=10)),
    legend.position = c(0.65, 0.12),
    legend.text = element_text(size=13),
    aspect.ratio = 0.8,
    text = element_text(size = 16, family = "Helvetica")
    ) +
xlab("(Lipid - IPH) volume (%)") +
ylab("Logits of symptoms")

plots <- append(plots, perc.lipid.iph.plot)
```

```{r}
lipid.iph.plot <- ggplot(lipid_iph, aes(volumes, logits)) +
geom_point(color="#003366") +
geom_smooth(span=0.4, se=TRUE, color="#FFC325", fill="#FFE299") +
theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    panel.border = element_rect(colour="black", fill=NA, size=0.5),
    axis.title = element_text(size=14),
    axis.title.x = element_text(margin=margin(t=10)),
    axis.title.y = element_text(margin=margin(r=10)),
    plot.title = element_text(hjust=0.5, size=16, margin=margin(b=10)),
    legend.position = c(0.65, 0.12),
    legend.text = element_text(size=13),
    aspect.ratio = 0.8,
    text = element_text(size = 16, family = "Helvetica")
    ) +
xlab("(Lipid - IPH) volume") +
ylab("Logits of symptoms")

plots <- append(plots, lipid.iph.plot)
```

```{r}
perc.mixed.plot <- ggplot(perc_mixed, aes(volumes, logits)) +
geom_point(color="#003366") +
geom_smooth(span=0.3, se=TRUE, color="#FFC325", fill="#FFE299") +
theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    panel.border = element_rect(colour="black", fill=NA, size=0.5),
    axis.title = element_text(size=14),
    axis.title.x = element_text(margin=margin(t=10)),
    axis.title.y = element_text(margin=margin(r=10)),
    plot.title = element_text(hjust=0.5, size=16, margin=margin(b=10)),
    legend.position = c(0.65, 0.12),
    legend.text = element_text(size=13),
    aspect.ratio = 0.8,
    text = element_text(size = 16, family = "Helvetica")
    ) +
xlab("Mixed volume (%)") +
ylab("Logits of symptoms")

plots <- append(plots, perc.mixed.plot)
```

```{r}
tiff("../output/plots/TIFF/loess.tiff", units="in", width=8, height=10, 
     res=500, 
     compression = "lzw",
     type="cairo")
g <- ggarrange(plotlist=lapply(list(ratio.plot, perc.iph.plot, iph.plot, 
                                    perc.lipid.iph.plot, lipid.iph.plot, 
                                    perc.mixed.plot), "+", theme(plot.margin=margin(5, 15, 5, 5))),
          nrow=3,
          ncol=2,
          labels=c("A", "B", "C", "D", "E", "F", "G"),
          font.label = list(size=16, family="Helvetica"))
#g2 <- annotate_figure(g2, top = textGrob("Assessment of model performance", gp=gpar(fontsize=20, font=1)))
g
dev.off()
```


```{r}
loess_model <- loess(scores ~ volumes, data=plaque_vol, span=.2)
smooth <- predict(loess_model, se=TRUE)
plaque_vol$lwl <- smooth$fit-1.96*smooth$se.fit
plaque_vol$upl <- smooth$fit+1.96*smooth$se.fit

#plot(plaque_vol$volumes, plaque_vol$scores, pch=19, main='Loess Regression Models')
#lines(smooth, x=plaque_vol$volumes, col='red')

ggplot(plaque_vol, aes(x = volumes, y = scores)) +
  geom_point() +
  geom_smooth(method = 'loess', span=0.2, ) +
  geom_line(aes(y = lwl), color = "red") +
  geom_line(aes(y = upl), color = "red")
```

